[package]
name = "oneTenCubed-hey"
version = "0.3.5"
edition = "2024"
rust-version = "1.95"
description = "keyword-based note retrieval tool"
readme = "README.md"
repository = "https://github.com/oneTenCubed/hey"
license = "MIT"

[dependencies]
dirs = "6.0.0"

[[bin]]
name = "hey"
path = "src/main.rs"
